# ==================== الترجمة (i18n) ====================
# اللغات المدعومة: العربية (ar), الفرنسية (fr), الإنجليزية (en)

translations = {
    'en': {
        # ===== عام =====
        'AI-Powered Medic': 'AI-Powered Medic',
        'AI-Powered Medic': 'AI-Powered Medic',
        'Home': 'Home',
        'Login': 'Login',
        'Register': 'Register',
        'Logout': 'Logout',
        'Profile': 'Profile',
        'Settings': 'Settings',
        'Dashboard': 'Dashboard',
        'Doctor': 'Doctor',
        'Patient': 'Patient',
        'All rights reserved': 'All rights reserved',
        'About': 'About',
        'Privacy': 'Privacy',
        'Terms': 'Terms',
        'Help': 'Help',
        'Search': 'Search',
        'Reset': 'Reset',
        'Cancel': 'Cancel',
        'Save': 'Save',
        'Save Changes': 'Save Changes',
        'Delete': 'Delete',
        'Edit': 'Edit',
        'View': 'View',
        'Back': 'Back',
        'Print': 'Print',
        'Share': 'Share',
        'Loading...': 'Loading...',
        'No data found': 'No data found',
        'Error': 'Error',
        'Success': 'Success',
        'Warning': 'Warning',
        'Information': 'Information',
        
        # ===== الصفحة الرئيسية =====
        'AI-Powered Medical Report Analyzer': 'AI-Powered Medical Report Analyzer',
        'Upload your medical reports and get instant AI-powered analysis in seconds': 'Upload your medical reports and get instant AI-powered analysis in seconds',
        'Quick Analysis': 'Quick Analysis',
        'Free': 'Free',
        'Try our AI analysis for free - No login required': 'Try our AI analysis for free - No login required',
        'Drag & Drop your medical images here': 'Drag & Drop your medical images here',
        'PNG, JPG, JPEG, GIF (Multiple images allowed)': 'PNG, JPG, JPEG, GIF (Multiple images allowed)',
        'Select Files': 'Select Files',
        'Analyze Reports': 'Analyze Reports',
        'AI is analyzing your medical documents...': 'AI is analyzing your medical documents...',
        'Analysis Results': 'Analysis Results',
        'Date': 'Date',
        'Conditions': 'Conditions',
        'Medications': 'Medications',
        'Alerts': 'Alerts',
        'Summary': 'Summary',
        'Upload images to see analysis results': 'Upload images to see analysis results',
        'Create an account to save and manage your reports.': 'Create an account to save and manage your reports.',
        'Register Now': 'Register Now',
        'AI Analysis': 'AI Analysis',
        'Intelligent analysis of medical reports using advanced AI algorithms': 'Intelligent analysis of medical reports using advanced AI algorithms',
        'Mobile Responsive': 'Mobile Responsive',
        'Access your reports from any device, anywhere': 'Access your reports from any device, anywhere',
        'Secure Storage': 'Secure Storage',
        'Your medical data is safely stored and encrypted': 'Your medical data is safely stored and encrypted',
        'Patients': 'Patients',
        'Reports Analyzed': 'Reports Analyzed',
        'Accuracy Rate': 'Accuracy Rate',
        'Support': 'Support',
        'Ready to get started?': 'Ready to get started?',
        'Join thousands of healthcare professionals using AI-Powered Medic': 'Join thousands of healthcare professionals using AI-Powered Medic',
        'Create Free Account': 'Create Free Account',
        
        # ===== المصادقة =====
        'Welcome Back': 'Welcome Back',
        'Sign in to continue to your account': 'Sign in to continue to your account',
        'Social Security Number (SSN)': 'Social Security Number (SSN)',
        'Email Address': 'Email Address',
        'Password': 'Password',
        'Remember me': 'Remember me',
        'Forgot Password?': 'Forgot Password?',
        'Login as Patient': 'Login as Patient',
        'Login as Doctor': 'Login as Doctor',
        "Don't have an account?": "Don't have an account?",
        'Create Account': 'Create Account',
        'Log In': 'Log In',
        
        # ===== التسجيل =====
        'Join MedAI and start managing your medical reports': 'Join MedAI and start managing your medical reports',
        'Full Name': 'Full Name',
        'John Doe': 'John Doe',
        'Age': 'Age',
        'Phone': 'Phone',
        'Account Type': 'Account Type',
        'Professional Information': 'Professional Information',
        'Commune of Working': 'Commune of Working',
        'Select Commune': 'Select Commune',
        'Specialty': 'Specialty',
        'Select Specialty': 'Select Specialty',
        'Clinic / Cabinet / Hospital Name': 'Clinic / Cabinet / Hospital Name',
        'Optional': 'Optional',
        'Full Address': 'Full Address',
        'Clinic Phone': 'Clinic Phone',
        'Clinic Email': 'Clinic Email',
        'Patient Information': 'Patient Information',
        'Find Your Doctor': 'Find Your Doctor',
        'Available Doctors': 'Available Doctors',
        'Find Doctors': 'Find Doctors',
        'No doctors found': 'No doctors found',
        'Already have an account?': 'Already have an account?',
        'Minimum 6 characters': 'Minimum 6 characters',
        'Cabinet Dr. Ahmed Benali': 'Cabinet Dr. Ahmed Benali',
        '123 Rue Didouche Mourad, Alger': '123 Rue Didouche Mourad, Alger',
        '+213 23 45 67 89': '+213 23 45 67 89',
        'cabinet@drbenali.com': 'cabinet@drbenali.com',
        '123-45-6789': '123-45-6789',
        'Required for patients. Format: 123-45-6789': 'Required for patients. Format: 123-45-6789',
        # ===== إضافات Step 1 =====
        'Choose Account Type': 'Choose Account Type',
        'Select whether you are a patient or a doctor': 'Select whether you are a patient or a doctor',
        'Access your medical records, view reports and prescriptions': 'Access your medical records, view reports and prescriptions',
        'Manage patients, create reports and prescriptions': 'Manage patients, create reports and prescriptions',
        'Selected': 'Selected',
        
        # ===== إضافات Step 2 =====
        'Basic Info': 'Basic Info',
        'Please provide your personal information': 'Please provide your personal information',
        'Confirm Password': 'Confirm Password',
        'Please re-enter your password': 'Please re-enter your password',
        'Passwords do not match': 'Passwords do not match',
        
        # ===== إضافات Step 3 =====
        'Details': 'Details',
        'Additional Information': 'Additional Information',
        'Please provide your professional or medical details': 'Please provide your professional or medical details',
        'Clinic / Cabinet Name': 'Clinic / Cabinet Name',
        'Commune': 'Commune',
        
        # ===== إضافات Step 4 =====
        'Confirm': 'Confirm',
        'Confirm Your Information': 'Confirm Your Information',
        'Please review your information before submitting': 'Please review your information before submitting',
        
        # ===== رسائل التحقق =====
        'Please select an account type': 'Please select an account type',
        'Please enter your full name': 'Please enter your full name',
        'Please enter your email address': 'Please enter your email address',
        'Please enter a valid email address': 'Please enter a valid email address',
        'Password must be at least 6 characters': 'Password must be at least 6 characters',
        'SSN is required for patient registration': 'SSN is required for patient registration',
        'Please select both commune and specialty': 'Please select both commune and specialty',
        'Error finding doctors': 'Error finding doctors',
        'You have already selected an account type. Use Back button to change.': 'You have already selected an account type. Use Back button to change.',
        
        # ===== أزرار التنقل =====
        'Back': 'Back',
        'Next': 'Next',
        'Create Account': 'Create Account',
        
        # ===== التحقق =====
        'Verify Your Email': 'Verify Your Email',
        "We've sent a verification code to your email": "We've sent a verification code to your email",
        'Enter Verification Code': 'Enter Verification Code',
        'Enter the 6-digit code sent to your email': 'Enter the 6-digit code sent to your email',
        'Code expires in': 'Code expires in',
        'Verify Email': 'Verify Email',
        "Didn't receive the code?": "Didn't receive the code?",
        'Resend Code': 'Resend Code',
        'Back to Register': 'Back to Register',
        'Check your spam folder': 'Check your spam folder',
        'Make sure your email is correct': 'Make sure your email is correct',
        
        # ===== نسيت كلمة المرور =====
        'No worries! We\'ll send you a reset code': 'No worries! We\'ll send you a reset code',
        "We'll send a 6-digit verification code to this email": "We'll send a 6-digit verification code to this email",
        'Send Reset Code': 'Send Reset Code',
        'Back to Login': 'Back to Login',
        'We respect your privacy. Your information is secure and will never be shared.': 'We respect your privacy. Your information is secure and will never be shared.',
        
        # ===== إعادة تعيين كلمة المرور =====
        'Reset Password': 'Reset Password',
        'Enter the code and your new password': 'Enter the code and your new password',
        'Verification Code': 'Verification Code',
        'New Password': 'New Password',
        'Confirm Password': 'Confirm Password',
        'Password Requirements:': 'Password Requirements:',
        'At least 6 characters': 'At least 6 characters',
        'Passwords must match': 'Passwords must match',
        'Request new code': 'Request new code',
        'For security reasons, this link will expire in 10 minutes': 'For security reasons, this link will expire in 10 minutes',
        
        # ===== لوحة تحكم الطبيب =====
        'Doctor Dashboard': 'Doctor Dashboard',
        'Total Patients': 'Total Patients',
        'Total Reports': 'Total Reports',
        'Prescriptions': 'Prescriptions',
        'Active Patients': 'Active Patients',
        'Search Filters': 'Search Filters',
        'Patient Name': 'Patient Name',
        'SSN': 'SSN',
        'Rx': 'Rx',
        'Last Report': 'Last Report',
        'Actions': 'Actions',
        'Verified': 'Verified',
        'Pending': 'Pending',
        'View Reports': 'View Reports',
        'Edit Patient': 'Edit Patient',
        'New Analysis': 'New Analysis',
        'Add Prescription': 'Add Prescription',
        'Remove': 'Remove',
        'No patients found': 'No patients found',
        'Add your first patient': 'Add your first patient',
        'Add Patient': 'Add Patient',
        'Statistics': 'Statistics',
        
        # ===== إضافة مريض =====
        'Add New Patient': 'Add New Patient',
        'Personal Information': 'Personal Information',
        'Create a patient account (with email and password)': 'Create a patient account (with email and password)',
        'The patient will receive a verification code by email': 'The patient will receive a verification code by email',
        'Same as above if not specified': 'Same as above if not specified',
        'Required only if creating an account': 'Required only if creating an account',
        'SSN is required when creating an account': 'SSN is required when creating an account',
        'Password must be at least 6 characters': 'Password must be at least 6 characters',
        
        # ===== تعديل مريض =====
        'Patient ID': 'Patient ID',
        'Created': 'Created',
        'Basic Information': 'Basic Information',
        'Medical Information': 'Medical Information',
        'Blood Type': 'Blood Type',
        'Select Blood Type': 'Select Blood Type',
        'Allergies': 'Allergies',
        'e.g., Penicillin, Peanuts, Latex': 'e.g., Penicillin, Peanuts, Latex',
        'Chronic Conditions': 'Chronic Conditions',
        'e.g., Hypertension, Diabetes, Asthma': 'e.g., Hypertension, Diabetes, Asthma',
        'Emergency Contact': 'Emergency Contact',
        'Contact Name': 'Contact Name',
        'Full name of emergency contact': 'Full name of emergency contact',
        'Contact Phone': 'Contact Phone',
        'Emergency phone number': 'Emergency phone number',
        'Danger Zone': 'Danger Zone',
        'Remove this patient from your list': 'Remove this patient from your list',
        'Remove Patient': 'Remove Patient',
        'Are you sure you want to remove this patient from your list?': 'Are you sure you want to remove this patient from your list?',
        'Patient name is required': 'Patient name is required',
        'Email is required for account access': 'Email is required for account access',
        'SSN cannot be changed after creation': 'SSN cannot be changed after creation',
        
        # ===== التحليل الطبي =====
        'Medical Analysis': 'Medical Analysis',
        'Upload Medical Documents': 'Upload Medical Documents',
        'Start Analysis': 'Start Analysis',
        'Save Report': 'Save Report',
        'Report saved successfully!': 'Report saved successfully!',
        'Error saving report': 'Error saving report',
        'None identified': 'None identified',
        'No alerts': 'No alerts',
        'Please select images to analyze': 'Please select images to analyze',
        'Analysis complete!': 'Analysis complete!',
        'Error during analysis': 'Error during analysis',
        
        # ===== الوصفات الطبية =====
        'New Prescription': 'New Prescription',
        'Diagnosis & Notes': 'Diagnosis & Notes',
        'Diagnosis': 'Diagnosis',
        'Enter diagnosis here...': 'Enter diagnosis here...',
        'Additional Notes': 'Additional Notes',
        'Additional instructions for the patient...': 'Additional instructions for the patient...',
        'Prescribed Medications': 'Prescribed Medications',
        'Medication': 'Medication',
        'Dosage': 'Dosage',
        'Frequency': 'Frequency',
        'Duration': 'Duration',
        'Instructions': 'Instructions',
        'Select medicine': 'Select medicine',
        'Select dosage': 'Select dosage',
        'Select frequency': 'Select frequency',
        'Select duration': 'Select duration',
        'Once daily': 'Once daily',
        'Twice daily': 'Twice daily',
        'Three times daily': 'Three times daily',
        'Four times daily': 'Four times daily',
        'Every 8 hours': 'Every 8 hours',
        'Every 12 hours': 'Every 12 hours',
        'As needed': 'As needed',
        'days': 'days',
        'e.g., Before meals': 'e.g., Before meals',
        'Add Medication': 'Add Medication',
        'AI Drug Interaction Analysis': 'AI Drug Interaction Analysis',
        'AI analyzing drug interactions...': 'AI analyzing drug interactions...',
        'No dangerous drug interactions detected': 'No dangerous drug interactions detected',
        'AI service unavailable. Please check interactions manually.': 'AI service unavailable. Please check interactions manually.',
        'Dosage Analysis': 'Dosage Analysis',
        'Active Ingredient': 'Active Ingredient',
        'Daily Dose': 'Daily Dose',
        'Safe Limit': 'Safe Limit',
        'Status': 'Status',
        'Warning': 'Warning',
        'Select medications to analyze': 'Select medications to analyze',
        'Save Prescription': 'Save Prescription',
        'At least one medication is required': 'At least one medication is required',
        'This prescription may not be safe! Please review.': 'This prescription may not be safe! Please review.',
        
        # ===== عرض الوصفة =====
        'Medical Prescription': 'Medical Prescription',
        'Prescription No': 'Prescription No',
        'Patient Name': 'Patient Name',
        'Weight': 'Weight',
        'Our Services': 'Our Services',
        'General Medical Consultations': 'General Medical Consultations',
        'Internal Medicine Examinations': 'Internal Medicine Examinations',
        'Blood & Urine Analysis': 'Blood & Urine Analysis',
        'ECG (Electrocardiogram)': 'ECG (Electrocardiogram)',
        'Pregnancy Follow-up Clinic': 'Pregnancy Follow-up Clinic',
        'Specialized Consultations': 'Specialized Consultations',
        'Doctor Information': 'Doctor Information',
        'Clinic Information': 'Clinic Information',
        "Doctor's Signature": "Doctor's Signature",
        'Clinic Stamp': 'Clinic Stamp',
        'Dear pharmacist or doctor, for any questions or errors in this prescription, please contact the clinic.': 'Dear pharmacist or doctor, for any questions or errors in this prescription, please contact the clinic.',
        
        # ===== إحصائيات الطبيب =====
        'Statistics Dashboard': 'Statistics Dashboard',
        'Reports by Month': 'Reports by Month',
        'Top Conditions': 'Top Conditions',
        'Patient Statistics': 'Patient Statistics',
        'Last Visit': 'Last Visit',
        'Export': 'Export',
        
        # ===== لوحة تحكم المريض =====
        'Welcome Back': 'Welcome Back',
        'Here is an overview of your medical records': 'Here is an overview of your medical records',
        'Medical Reports': 'Medical Reports',
        'Doctors': 'Doctors',
        'AI Analyses': 'AI Analyses',
        'Recent Medical Reports': 'Recent Medical Reports',
        'My Doctors': 'My Doctors',
        'Recent Prescriptions': 'Recent Prescriptions',
        'Medical Alerts': 'Medical Alerts',
        'View All Reports': 'View All Reports',
        'My Prescriptions': 'My Prescriptions',
        'Report Details': 'Report Details',
        'No medical reports yet': 'No medical reports yet',
        'Visit your doctor to get your first analysis': 'Visit your doctor to get your first analysis',
        'No doctors assigned yet': 'No doctors assigned yet',
        'No prescriptions yet': 'No prescriptions yet',
        'View all reports': 'View all reports',
        'View all prescriptions': 'View all prescriptions',
        'General Practitioner': 'General Practitioner',
        
        # ===== الإعدادات =====
        'Account Settings': 'Account Settings',
        'Manage your personal information and account preferences': 'Manage your personal information and account preferences',
        'Change Password': 'Change Password',
        'Preferences': 'Preferences',
        'Delete Account': 'Delete Account',
        'Current Password': 'Current Password',
        'Update Password': 'Update Password',
        'Language': 'Language',
        'Notifications': 'Notifications',
        'Receive email alerts': 'Receive email alerts',
        'Receive appointment reminders': 'Receive appointment reminders',
        'Save Preferences': 'Save Preferences',
        'Are you sure you want to delete your account? This action cannot be undone.': 'Are you sure you want to delete your account? This action cannot be undone.',
        'Enter your password to confirm': 'Enter your password to confirm',
        'Clinic Logo': 'Clinic Logo',
        'Upload Logo': 'Upload Logo',
        'Remove Logo': 'Remove Logo',
        'Recommended size: 200x200px. Formats: PNG, JPG, JPEG, GIF, SVG': 'Recommended size: 200x200px. Formats: PNG, JPG, JPEG, GIF, SVG',
        'Are you sure you want to remove the clinic logo?': 'Are you sure you want to remove the clinic logo?',
        
        # ===== وصفات المريض =====
        'My Prescriptions': 'My Prescriptions',
        'View and manage all your prescriptions': 'View and manage all your prescriptions',
        'Total Prescriptions': 'Total Prescriptions',
        'Active Prescriptions': 'Active Prescriptions',
        'Expired Prescriptions': 'Expired Prescriptions',
        'All Prescriptions': 'All Prescriptions',
        'Active': 'Active',
        'Expired': 'Expired',
        'No medications listed': 'No medications listed',
        'Issued on': 'Issued on',
        'Important Information': 'Important Information',
        'A prescription expires after the indicated validity period': 'A prescription expires after the indicated validity period',
        'Contact your doctor for a renewal if needed': 'Contact your doctor for a renewal if needed',
        'You can print your prescriptions or share them via email': 'You can print your prescriptions or share them via email',
        'Keep your prescriptions safe and do not share them with unauthorized persons': 'Keep your prescriptions safe and do not share them with unauthorized persons',
        'Share Prescription': 'Share Prescription',
        'Enter the email address to share this prescription with:': 'Enter the email address to share this prescription with:',
        'Send': 'Send',
        'Prescription sent successfully!': 'Prescription sent successfully!',
        'Error sending prescription': 'Error sending prescription',
        'Please enter an email address': 'Please enter an email address',
        'Please enter a valid email address': 'Please enter a valid email address',
        
        # ===== أطباء المريض =====
        'List of healthcare professionals managing your medical records': 'List of healthcare professionals managing your medical records',
        'Total Doctors': 'Total Doctors',
        'Total Medical Reports': 'Total Medical Reports',
        'Your Healthcare Team': 'Your Healthcare Team',
        'Contact': 'Contact',
        'About Your Healthcare Team': 'About Your Healthcare Team',
        'Your doctors have access to your medical records': 'Your doctors have access to your medical records',
        'They can create prescriptions and medical reports for you': 'They can create prescriptions and medical reports for you',
        'You can contact them using the email or phone provided': 'You can contact them using the email or phone provided',
        'Your medical data is protected and shared only with authorized doctors': 'Your medical data is protected and shared only with authorized doctors',
        'Doctor Reports': 'Doctor Reports',
        'No reports found from this doctor': 'No reports found from this doctor',
        'Error loading reports': 'Error loading reports',
        'conditions': 'conditions',
        'medications': 'medications',
        'No summary': 'No summary',
    },
    
    'fr': {
        # ===== Général =====
        'AI-Powered Medic': 'AI-Powered Medic',
        'Home': 'Accueil',
        'Login': 'Connexion',
        'Register': 'S\'inscrire',
        'Logout': 'Déconnexion',
        'Profile': 'Profil',
        'Settings': 'Paramètres',
        'Dashboard': 'Tableau de bord',
        'Doctor': 'Médecin',
        'Patient': 'Patient',
        'All rights reserved': 'Tous droits réservés',
        'About': 'À propos',
        'Privacy': 'Confidentialité',
        'Terms': 'Conditions',
        'Help': 'Aide',
        'Search': 'Rechercher',
        'Reset': 'Réinitialiser',
        'Cancel': 'Annuler',
        'Save': 'Enregistrer',
        'Save Changes': 'Enregistrer les modifications',
        'Delete': 'Supprimer',
        'Edit': 'Modifier',
        'View': 'Voir',
        'Back': 'Retour',
        'Print': 'Imprimer',
        'Share': 'Partager',
        'Loading...': 'Chargement...',
        'No data found': 'Aucune donnée trouvée',
        'Error': 'Erreur',
        'Success': 'Succès',
        'Warning': 'Attention',
        'Information': 'Information',
        
        # ===== Page d\'accueil =====
        'AI-Powered Medical Report Analyzer': 'Analyseur de rapports médicaux AI',
        'Upload your medical reports and get instant AI-powered analysis in seconds': 'Téléchargez vos rapports médicaux et obtenez une analyse instantanée par IA',
        'Quick Analysis': 'Analyse rapide',
        'Free': 'Gratuit',
        'Try our AI analysis for free - No login required': 'Essayez notre analyse IA gratuitement - Sans inscription',
        'Drag & Drop your medical images here': 'Glissez-déposez vos images médicales ici',
        'PNG, JPG, JPEG, GIF (Multiple images allowed)': 'PNG, JPG, JPEG, GIF (Plusieurs images autorisées)',
        'Select Files': 'Sélectionner les fichiers',
        'Analyze Reports': 'Analyser les rapports',
        'AI is analyzing your medical documents...': 'L\'IA analyse vos documents médicaux...',
        'Analysis Results': 'Résultats de l\'analyse',
        'Date': 'Date',
        'Conditions': 'Conditions',
        'Medications': 'Médicaments',
        'Alerts': 'Alertes',
        'Summary': 'Résumé',
        'Upload images to see analysis results': 'Téléchargez des images pour voir les résultats',
        'Create an account to save and manage your reports.': 'Créez un compte pour sauvegarder et gérer vos rapports.',
        'Register Now': 'S\'inscrire maintenant',
        'AI Analysis': 'Analyse IA',
        'Intelligent analysis of medical reports using advanced AI algorithms': 'Analyse intelligente des rapports médicaux avec IA',
        'Mobile Responsive': 'Adapté mobile',
        'Access your reports from any device, anywhere': 'Accédez à vos rapports depuis n\'importe quel appareil',
        'Secure Storage': 'Stockage sécurisé',
        'Your medical data is safely stored and encrypted': 'Vos données médicales sont stockées et chiffrées',
        'Patients': 'Patients',
        'Reports Analyzed': 'Rapports analysés',
        'Accuracy Rate': 'Taux de précision',
        'Support': 'Support',
        'Ready to get started?': 'Prêt à commencer ?',
        'Join thousands of healthcare professionals using AI-Powered Medic': 'Rejoignez des milliers de professionnels de santé',
        'Create Free Account': 'Créer un compte gratuit',
        
        # ===== Authentification =====
        'Welcome Back': 'Bon retour',
        'Sign in to continue to your account': 'Connectez-vous pour continuer',
        'Social Security Number (SSN)': 'Numéro de sécurité sociale (NSS)',
        'Email Address': 'Adresse e-mail',
        'Password': 'Mot de passe',
        'Remember me': 'Se souvenir de moi',
        'Forgot Password?': 'Mot de passe oublié ?',
        'Login as Patient': 'Se connecter comme patient',
        'Login as Doctor': 'Se connecter comme médecin',
        "Don't have an account?": "Vous n'avez pas de compte ?",
        'Create Account': 'Créer un compte',
        'Log In': 'Se connecter',
        
        # ===== Inscription =====
        'Join MedAI and start managing your medical reports': 'Rejoignez MedAI et gérez vos rapports médicaux',
        'Full Name': 'Nom complet',
        'John Doe': 'Jean Dupont',
        'Age': 'Âge',
        'Phone': 'Téléphone',
        'Account Type': 'Type de compte',
        'Professional Information': 'Informations professionnelles',
        'Commune of Working': 'Commune de travail',
        'Select Commune': 'Sélectionner une commune',
        'Specialty': 'Spécialité',
        'Select Specialty': 'Sélectionner une spécialité',
        'Clinic / Cabinet / Hospital Name': 'Nom du cabinet / clinique / hôpital',
        'Optional': 'Optionnel',
        'Full Address': 'Adresse complète',
        'Clinic Phone': 'Téléphone du cabinet',
        'Clinic Email': 'Email du cabinet',
        'Patient Information': 'Informations patient',
        'Find Your Doctor': 'Trouver votre médecin',
        'Available Doctors': 'Médecins disponibles',
        'Find Doctors': 'Trouver des médecins',
        'No doctors found': 'Aucun médecin trouvé',
        'Already have an account?': 'Déjà un compte ?',
        'Minimum 6 characters': 'Minimum 6 caractères',
        'Cabinet Dr. Ahmed Benali': 'Cabinet Dr. Ahmed Benali',
        '123 Rue Didouche Mourad, Alger': '123 Rue Didouche Mourad, Alger',
        '+213 23 45 67 89': '+213 23 45 67 89',
        'cabinet@drbenali.com': 'cabinet@drbenali.com',
        '123-45-6789': '123-45-6789',
        'Required for patients. Format: 123-45-6789': 'Obligatoire pour les patients. Format: 123-45-6789',

        # ===== إضافات Step 1 =====
        'Choose Account Type': 'Choisissez le type de compte',
        'Select whether you are a patient or a doctor': 'Sélectionnez si vous êtes un patient ou un médecin',
        'Access your medical records, view reports and prescriptions': 'Accédez à vos dossiers médicaux, consultez les rapports et prescriptions',
        'Manage patients, create reports and prescriptions': 'Gérez les patients, créez des rapports et des prescriptions',
        'Selected': 'Sélectionné',
        
        # ===== إضافات Step 2 =====
        'Basic Info': 'Infos de base',
        'Please provide your personal information': 'Veuillez fournir vos informations personnelles',
        'Confirm Password': 'Confirmer le mot de passe',
        'Please re-enter your password': 'Veuillez ressaisir votre mot de passe',
        'Passwords do not match': 'Les mots de passe ne correspondent pas',
        
        # ===== إضافات Step 3 =====
        'Details': 'Détails',
        'Additional Information': 'Informations supplémentaires',
        'Please provide your professional or medical details': 'Veuillez fournir vos détails professionnels ou médicaux',
        'Clinic / Cabinet Name': 'Nom du cabinet',
        'Commune': 'Commune',
        
        # ===== إضافات Step 4 =====
        'Confirm': 'Confirmer',
        'Confirm Your Information': 'Confirmez vos informations',
        'Please review your information before submitting': 'Veuillez vérifier vos informations avant de soumettre',
        
        # ===== رسائل التحقق =====
        'Please select an account type': 'Veuillez sélectionner un type de compte',
        'Please enter your full name': 'Veuillez entrer votre nom complet',
        'Please enter your email address': 'Veuillez entrer votre adresse e-mail',
        'Please enter a valid email address': 'Veuillez entrer une adresse e-mail valide',
        'Password must be at least 6 characters': 'Le mot de passe doit comporter au moins 6 caractères',
        'SSN is required for patient registration': 'Le NSS est obligatoire pour l\'inscription des patients',
        'Please select both commune and specialty': 'Veuillez sélectionner la commune et la spécialité',
        'Error finding doctors': 'Erreur lors de la recherche des médecins',
        'You have already selected an account type. Use Back button to change.': 'Vous avez déjà sélectionné un type de compte. Utilisez le bouton Retour pour changer.',
        
        # ===== أزرار التنقل =====
        'Back': 'Retour',
        'Next': 'Suivant',
        'Create Account': 'Créer un compte',
        
        # ===== Vérification =====
        'Verify Your Email': 'Vérifiez votre e-mail',
        "We've sent a verification code to your email": "Un code de vérification a été envoyé à votre e-mail",
        'Enter Verification Code': 'Entrez le code de vérification',
        'Enter the 6-digit code sent to your email': 'Entrez le code à 6 chiffres reçu par e-mail',
        'Code expires in': 'Code expire dans',
        'Verify Email': 'Vérifier l\'e-mail',
        "Didn't receive the code?": "Vous n'avez pas reçu le code ?",
        'Resend Code': 'Renvoyer le code',
        'Back to Register': 'Retour à l\'inscription',
        'Check your spam folder': 'Vérifiez vos spams',
        'Make sure your email is correct': 'Assurez-vous que votre e-mail est correct',
        
        # ===== Mot de passe oublié =====
        'No worries! We\'ll send you a reset code': 'Pas de souci ! Nous vous enverrons un code',
        "We'll send a 6-digit verification code to this email": "Un code à 6 chiffres sera envoyé à cet e-mail",
        'Send Reset Code': 'Envoyer le code',
        'Back to Login': 'Retour à la connexion',
        'We respect your privacy. Your information is secure and will never be shared.': 'Nous respectons votre vie privée. Vos informations sont sécurisées.',
        
        # ===== Réinitialisation du mot de passe =====
        'Reset Password': 'Réinitialiser le mot de passe',
        'Enter the code and your new password': 'Entrez le code et votre nouveau mot de passe',
        'Verification Code': 'Code de vérification',
        'New Password': 'Nouveau mot de passe',
        'Confirm Password': 'Confirmer le mot de passe',
        'Password Requirements:': 'Exigences du mot de passe :',
        'At least 6 characters': 'Au moins 6 caractères',
        'Passwords must match': 'Les mots de passe doivent correspondre',
        'Request new code': 'Demander un nouveau code',
        'For security reasons, this link will expire in 10 minutes': 'Pour des raisons de sécurité, ce lien expirera dans 10 minutes',
        
        # ===== Tableau de bord médecin =====
        'Doctor Dashboard': 'Tableau de bord médecin',
        'Total Patients': 'Total patients',
        'Total Reports': 'Total rapports',
        'Prescriptions': 'Prescriptions',
        'Active Patients': 'Patients actifs',
        'Search Filters': 'Filtres de recherche',
        'Patient Name': 'Nom du patient',
        'SSN': 'NSS',
        'Rx': 'Ordo',
        'Last Report': 'Dernier rapport',
        'Actions': 'Actions',
        'Verified': 'Vérifié',
        'Pending': 'En attente',
        'View Reports': 'Voir les rapports',
        'Edit Patient': 'Modifier le patient',
        'New Analysis': 'Nouvelle analyse',
        'Add Prescription': 'Ajouter prescription',
        'Remove': 'Retirer',
        'No patients found': 'Aucun patient trouvé',
        'Add your first patient': 'Ajouter votre premier patient',
        'Add Patient': 'Ajouter patient',
        'Statistics': 'Statistiques',
        
        # ===== Ajouter patient =====
        'Add New Patient': 'Ajouter un nouveau patient',
        'Personal Information': 'Informations personnelles',
        'Create a patient account (with email and password)': 'Créer un compte patient (avec e-mail et mot de passe)',
        'The patient will receive a verification code by email': 'Le patient recevra un code de vérification par e-mail',
        'Same as above if not specified': 'Identique à ci-dessus si non spécifié',
        'Required only if creating an account': 'Requis uniquement si création d\'un compte',
        'SSN is required when creating an account': 'Le NSS est requis lors de la création d\'un compte',
        'Password must be at least 6 characters': 'Le mot de passe doit comporter au moins 6 caractères',
        
        # ===== Modifier patient =====
        'Patient ID': 'ID patient',
        'Created': 'Créé le',
        'Basic Information': 'Informations de base',
        'Medical Information': 'Informations médicales',
        'Blood Type': 'Groupe sanguin',
        'Select Blood Type': 'Sélectionner le groupe sanguin',
        'Allergies': 'Allergies',
        'e.g., Penicillin, Peanuts, Latex': 'Ex: Pénicilline, Arachides, Latex',
        'Chronic Conditions': 'Maladies chroniques',
        'e.g., Hypertension, Diabetes, Asthma': 'Ex: Hypertension, Diabète, Asthme',
        'Emergency Contact': 'Contact d\'urgence',
        'Contact Name': 'Nom du contact',
        'Full name of emergency contact': 'Nom complet du contact d\'urgence',
        'Contact Phone': 'Téléphone du contact',
        'Emergency phone number': 'Numéro d\'urgence',
        'Danger Zone': 'Zone dangereuse',
        'Remove this patient from your list': 'Retirer ce patient de votre liste',
        'Remove Patient': 'Retirer le patient',
        'Are you sure you want to remove this patient from your list?': 'Voulez-vous vraiment retirer ce patient de votre liste ?',
        'Patient name is required': 'Le nom du patient est requis',
        'Email is required for account access': 'L\'e-mail est requis pour l\'accès au compte',
        'SSN cannot be changed after creation': 'Le NSS ne peut pas être modifié après création',
        
        # ===== Analyse médicale =====
        'Medical Analysis': 'Analyse médicale',
        'Upload Medical Documents': 'Télécharger des documents médicaux',
        'Start Analysis': 'Commencer l\'analyse',
        'Save Report': 'Enregistrer le rapport',
        'Report saved successfully!': 'Rapport enregistré avec succès !',
        'Error saving report': 'Erreur lors de l\'enregistrement',
        'None identified': 'Aucun identifié',
        'No alerts': 'Aucune alerte',
        'Please select images to analyze': 'Veuillez sélectionner des images à analyser',
        'Analysis complete!': 'Analyse terminée !',
        'Error during analysis': 'Erreur pendant l\'analyse',
        
        # ===== Prescriptions =====
        'New Prescription': 'Nouvelle prescription',
        'Diagnosis & Notes': 'Diagnostic et notes',
        'Diagnosis': 'Diagnostic',
        'Enter diagnosis here...': 'Entrez le diagnostic ici...',
        'Additional Notes': 'Notes supplémentaires',
        'Additional instructions for the patient...': 'Instructions supplémentaires pour le patient...',
        'Prescribed Medications': 'Médicaments prescrits',
        'Medication': 'Médicament',
        'Dosage': 'Posologie',
        'Frequency': 'Fréquence',
        'Duration': 'Durée',
        'Instructions': 'Instructions',
        'Select medicine': 'Sélectionner un médicament',
        'Select dosage': 'Sélectionner la posologie',
        'Select frequency': 'Sélectionner la fréquence',
        'Select duration': 'Sélectionner la durée',
        'Once daily': 'Une fois par jour',
        'Twice daily': 'Deux fois par jour',
        'Three times daily': 'Trois fois par jour',
        'Four times daily': 'Quatre fois par jour',
        'Every 8 hours': 'Toutes les 8 heures',
        'Every 12 hours': 'Toutes les 12 heures',
        'As needed': 'Au besoin',
        'days': 'jours',
        'e.g., Before meals': 'Ex: Avant les repas',
        'Add Medication': 'Ajouter un médicament',
        'AI Drug Interaction Analysis': 'Analyse des interactions médicamenteuses IA',
        'AI analyzing drug interactions...': 'L\'IA analyse les interactions...',
        'No dangerous drug interactions detected': 'Aucune interaction dangereuse détectée',
        'AI service unavailable. Please check interactions manually.': 'Service IA indisponible. Vérifiez manuellement.',
        'Dosage Analysis': 'Analyse posologique',
        'Active Ingredient': 'Principe actif',
        'Daily Dose': 'Dose quotidienne',
        'Safe Limit': 'Limite sûre',
        'Status': 'Statut',
        'Warning': 'Avertissement',
        'Select medications to analyze': 'Sélectionnez les médicaments à analyser',
        'Save Prescription': 'Enregistrer la prescription',
        'At least one medication is required': 'Au moins un médicament est requis',
        'This prescription may not be safe! Please review.': 'Cette prescription peut ne pas être sûre ! Veuillez vérifier.',
        
        # ===== Voir prescription =====
        'Medical Prescription': 'Prescription médicale',
        'Prescription No': 'N° Ordonnance',
        'Patient Name': 'Nom du patient',
        'Weight': 'Poids',
        'Our Services': 'Nos services',
        'General Medical Consultations': 'Consultations médicales générales',
        'Internal Medicine Examinations': 'Examens de médecine interne',
        'Blood & Urine Analysis': 'Analyses de sang et d\'urine',
        'ECG (Electrocardiogram)': 'Électrocardiogramme (ECG)',
        'Pregnancy Follow-up Clinic': 'Suivi de grossesse',
        'Specialized Consultations': 'Consultations spécialisées',
        'Doctor Information': 'Informations médecin',
        'Clinic Information': 'Informations cabinet',
        "Doctor's Signature": 'Signature du médecin',
        'Clinic Stamp': 'Cachet du cabinet',
        'Dear pharmacist or doctor, for any questions or errors in this prescription, please contact the clinic.': 'Cher pharmacien ou médecin, pour toute question ou erreur, veuillez contacter le cabinet.',
        
        # ===== Statistiques médecin =====
        'Statistics Dashboard': 'Tableau de bord statistiques',
        'Reports by Month': 'Rapports par mois',
        'Top Conditions': 'Principales pathologies',
        'Patient Statistics': 'Statistiques patients',
        'Last Visit': 'Dernière visite',
        'Export': 'Exporter',
        
        # ===== Tableau de bord patient =====
        'Welcome Back': 'Bon retour',
        'Here is an overview of your medical records': 'Aperçu de vos dossiers médicaux',
        'Medical Reports': 'Rapports médicaux',
        'Doctors': 'Médecins',
        'AI Analyses': 'Analyses IA',
        'Recent Medical Reports': 'Rapports médicaux récents',
        'My Doctors': 'Mes médecins',
        'Recent Prescriptions': 'Prescriptions récentes',
        'Medical Alerts': 'Alertes médicales',
        'View All Reports': 'Voir tous les rapports',
        'My Prescriptions': 'Mes prescriptions',
        'Report Details': 'Détails du rapport',
        'No medical reports yet': 'Pas encore de rapports médicaux',
        'Visit your doctor to get your first analysis': 'Consultez votre médecin pour votre première analyse',
        'No doctors assigned yet': 'Aucun médecin assigné',
        'No prescriptions yet': 'Pas encore de prescriptions',
        'View all reports': 'Voir tous les rapports',
        'View all prescriptions': 'Voir toutes les prescriptions',
        'General Practitioner': 'Médecin généraliste',
        
        # ===== Paramètres =====
        'Account Settings': 'Paramètres du compte',
        'Manage your personal information and account preferences': 'Gérez vos informations personnelles et préférences',
        'Change Password': 'Changer le mot de passe',
        'Preferences': 'Préférences',
        'Delete Account': 'Supprimer le compte',
        'Current Password': 'Mot de passe actuel',
        'Update Password': 'Mettre à jour le mot de passe',
        'Language': 'Langue',
        'Notifications': 'Notifications',
        'Receive email alerts': 'Recevoir des alertes e-mail',
        'Receive appointment reminders': 'Recevoir des rappels de rendez-vous',
        'Save Preferences': 'Enregistrer les préférences',
        'Are you sure you want to delete your account? This action cannot be undone.': 'Voulez-vous vraiment supprimer votre compte ? Cette action est irréversible.',
        'Enter your password to confirm': 'Entrez votre mot de passe pour confirmer',
        'Clinic Logo': 'Logo du cabinet',
        'Upload Logo': 'Télécharger le logo',
        'Remove Logo': 'Supprimer le logo',
        'Recommended size: 200x200px. Formats: PNG, JPG, JPEG, GIF, SVG': 'Taille recommandée: 200x200px. Formats: PNG, JPG, JPEG, GIF, SVG',
        'Are you sure you want to remove the clinic logo?': 'Voulez-vous vraiment supprimer le logo du cabinet ?',
        
        # ===== Prescriptions patient =====
        'My Prescriptions': 'Mes prescriptions',
        'View and manage all your prescriptions': 'Voir et gérer toutes vos prescriptions',
        'Total Prescriptions': 'Total prescriptions',
        'Active Prescriptions': 'Prescriptions actives',
        'Expired Prescriptions': 'Prescriptions expirées',
        'All Prescriptions': 'Toutes les prescriptions',
        'Active': 'Active',
        'Expired': 'Expirée',
        'No medications listed': 'Aucun médicament listé',
        'Issued on': 'Délivrée le',
        'Important Information': 'Informations importantes',
        'A prescription expires after the indicated validity period': 'Une prescription expire après la période indiquée',
        'Contact your doctor for a renewal if needed': 'Contactez votre médecin pour un renouvellement',
        'You can print your prescriptions or share them via email': 'Vous pouvez imprimer ou partager vos prescriptions par e-mail',
        'Keep your prescriptions safe and do not share them with unauthorized persons': 'Gardez vos prescriptions en sécurité',
        'Share Prescription': 'Partager la prescription',
        'Enter the email address to share this prescription with:': 'Entrez l\'adresse e-mail pour partager :',
        'Send': 'Envoyer',
        'Prescription sent successfully!': 'Prescription envoyée avec succès !',
        'Error sending prescription': 'Erreur lors de l\'envoi',
        'Please enter an email address': 'Veuillez entrer une adresse e-mail',
        'Please enter a valid email address': 'Veuillez entrer une adresse e-mail valide',
        
        # ===== Médecins patient =====
        'List of healthcare professionals managing your medical records': 'Liste des professionnels gérant vos dossiers',
        'Total Doctors': 'Total médecins',
        'Total Medical Reports': 'Total rapports médicaux',
        'Your Healthcare Team': 'Votre équipe de soins',
        'Contact': 'Contacter',
        'About Your Healthcare Team': 'À propos de votre équipe de soins',
        'Your doctors have access to your medical records': 'Vos médecins ont accès à vos dossiers médicaux',
        'They can create prescriptions and medical reports for you': 'Ils peuvent créer des prescriptions pour vous',
        'You can contact them using the email or phone provided': 'Vous pouvez les contacter par e-mail ou téléphone',
        'Your medical data is protected and shared only with authorized doctors': 'Vos données sont protégées',
        'Doctor Reports': 'Rapports du médecin',
        'No reports found from this doctor': 'Aucun rapport trouvé',
        'Error loading reports': 'Erreur de chargement',
        'conditions': 'pathologies',
        'medications': 'médicaments',
        'No summary': 'Pas de résumé',
    },
    
    'ar': {
        # ===== عام =====
        'AI-Powered Medic': 'AI-Powered Medic',
        'Home': 'الرئيسية',
        'Login': 'تسجيل الدخول',
        'Register': 'إنشاء حساب',
        'Logout': 'تسجيل الخروج',
        'Profile': 'الملف الشخصي',
        'Settings': 'الإعدادات',
        'Dashboard': 'لوحة التحكم',
        'Doctor': 'طبيب',
        'Patient': 'مريض',
        'All rights reserved': 'جميع الحقوق محفوظة',
        'About': 'عن الموقع',
        'Privacy': 'الخصوصية',
        'Terms': 'الشروط',
        'Help': 'المساعدة',
        'Search': 'بحث',
        'Reset': 'إعادة تعيين',
        'Cancel': 'إلغاء',
        'Save': 'حفظ',
        'Save Changes': 'حفظ التغييرات',
        'Delete': 'حذف',
        'Edit': 'تعديل',
        'View': 'عرض',
        'Back': 'رجوع',
        'Print': 'طباعة',
        'Share': 'مشاركة',
        'Loading...': 'جاري التحميل...',
        'No data found': 'لا توجد بيانات',
        'Error': 'خطأ',
        'Success': 'تم بنجاح',
        'Warning': 'تنبيه',
        'Information': 'معلومات',
        
        # ===== الصفحة الرئيسية =====
        'AI-Powered Medical Report Analyzer': 'محلل التقارير الطبية بالذكاء الاصطناعي',
        'Upload your medical reports and get instant AI-powered analysis in seconds': 'حمّل تقاريرك الطبية واحصل على تحليل فوري بالذكاء الاصطناعي',
        'Quick Analysis': 'تحليل سريع',
        'Free': 'مجاني',
        'Try our AI analysis for free - No login required': 'جرب التحليل بالذكاء الاصطناعي مجاناً - بدون تسجيل دخول',
        'Drag & Drop your medical images here': 'اسحب وأفلت صورك الطبية هنا',
        'PNG, JPG, JPEG, GIF (Multiple images allowed)': 'PNG, JPG, JPEG, GIF (يمكن رفع عدة صور)',
        'Select Files': 'اختر الملفات',
        'Analyze Reports': 'تحليل التقارير',
        'AI is analyzing your medical documents...': 'الذكاء الاصطناعي يحلل مستنداتك الطبية...',
        'Analysis Results': 'نتائج التحليل',
        'Date': 'التاريخ',
        'Conditions': 'الحالات الطبية',
        'Medications': 'الأدوية',
        'Alerts': 'تنبيهات',
        'Summary': 'ملخص',
        'Upload images to see analysis results': 'حمّل الصور لمشاهدة نتائج التحليل',
        'Create an account to save and manage your reports.': 'أنشئ حساباً لحفظ وإدارة تقاريرك.',
        'Register Now': 'سجل الآن',
        'AI Analysis': 'تحليل الذكاء الاصطناعي',
        'Intelligent analysis of medical reports using advanced AI algorithms': 'تحليل ذكي للتقارير الطبية باستخدام خوارزميات الذكاء الاصطناعي',
        'Mobile Responsive': 'متوافق مع الجوال',
        'Access your reports from any device, anywhere': 'يمكنك الوصول إلى تقاريرك من أي جهاز وفي أي مكان',
        'Secure Storage': 'تخزين آمن',
        'Your medical data is safely stored and encrypted': 'بياناتك الطبية مخزنة ومشفرة بأمان',
        'Patients': 'مرضى',
        'Reports Analyzed': 'تقارير تم تحليلها',
        'Accuracy Rate': 'نسبة الدقة',
        'Support': 'الدعم',
        'Ready to get started?': 'مستعد للبدء؟',
        'Join thousands of healthcare professionals using AI-Powered Medic': 'انضم إلى آلاف المهنيين الصحيين باستخدام AI-Powered Medic',
        'Create Free Account': 'إنشاء حساب مجاني',
        
        # ===== المصادقة =====
        'Welcome Back': 'مرحباً بعودتك',
        'Sign in to continue to your account': 'سجل الدخول للمتابعة إلى حسابك',
        'Social Security Number (SSN)': 'رقم الضمان الاجتماعي',
        'Email Address': 'البريد الإلكتروني',
        'Password': 'كلمة المرور',
        'Remember me': 'تذكرني',
        'Forgot Password?': 'نسيت كلمة المرور؟',
        'Login as Patient': 'تسجيل دخول كمريض',
        'Login as Doctor': 'تسجيل دخول كطبيب',
        "Don't have an account?": "ليس لديك حساب؟",
        'Create Account': 'إنشاء حساب',
        'Log In': 'تسجيل دخول',
        
        # ===== التسجيل =====
        'Join MedAI and start managing your medical reports': 'انضم إلى MedAI وابدأ في إدارة تقاريرك الطبية',
        'Full Name': 'الاسم الكامل',
        'John Doe': 'جون دو',
        'Age': 'العمر',
        'Phone': 'الهاتف',
        'Account Type': 'نوع الحساب',
        'Professional Information': 'المعلومات المهنية',
        'Commune of Working': 'بلدية العمل',
        'Select Commune': 'اختر البلدية',
        'Specialty': 'التخصص',
        'Select Specialty': 'اختر التخصص',
        'Clinic / Cabinet / Hospital Name': 'اسم العيادة / المركز / المستشفى',
        'Optional': 'اختياري',
        'Full Address': 'العنوان الكامل',
        'Clinic Phone': 'هاتف العيادة',
        'Clinic Email': 'بريد العيادة',
        'Patient Information': 'معلومات المريض',
        'Find Your Doctor': 'ابحث عن طبيبك',
        'Available Doctors': 'الأطباء المتاحون',
        'Find Doctors': 'ابحث عن أطباء',
        'No doctors found': 'لم يتم العثور على أطباء',
        'Already have an account?': 'لديك حساب بالفعل؟',
        'Minimum 6 characters': '6 أحرف على الأقل',
        'Cabinet Dr. Ahmed Benali': 'عيادة د. أحمد بن علي',
        '123 Rue Didouche Mourad, Alger': '123 شارع ديدوش مراد، الجزائر',
        '+213 23 45 67 89': '+213 23 45 67 89',
        'cabinet@drbenali.com': 'cabinet@drbenali.com',
        '123-45-6789': '123-45-6789',
        'Required for patients. Format: 123-45-6789': 'مطلوب للمرضى. التنسيق: 123-45-6789',

         # ===== إضافات Step 1 =====
        'Choose Account Type': 'اختر نوع الحساب',
        'Select whether you are a patient or a doctor': 'اختر ما إذا كنت مريضاً أو طبيباً',
        'Access your medical records, view reports and prescriptions': 'الوصول إلى سجلاتك الطبية، وعرض التقارير والوصفات',
        'Manage patients, create reports and prescriptions': 'إدارة المرضى، إنشاء التقارير والوصفات الطبية',
        'Selected': 'تم الاختيار',
        
        # ===== إضافات Step 2 =====
        'Basic Info': 'المعلومات الأساسية',
        'Please provide your personal information': 'الرجاء تقديم معلوماتك الشخصية',
        'Confirm Password': 'تأكيد كلمة المرور',
        'Please re-enter your password': 'الرجاء إعادة إدخال كلمة المرور',
        'Passwords do not match': 'كلمات المرور غير متطابقة',
        
        # ===== إضافات Step 3 =====
        'Details': 'التفاصيل',
        'Additional Information': 'معلومات إضافية',
        'Please provide your professional or medical details': 'الرجاء تقديم تفاصيلك المهنية أو الطبية',
        'Clinic / Cabinet Name': 'اسم العيادة',
        'Commune': 'البلدية',
        
        # ===== إضافات Step 4 =====
        'Confirm': 'تأكيد',
        'Confirm Your Information': 'تأكيد معلوماتك',
        'Please review your information before submitting': 'الرجاء مراجعة معلوماتك قبل الإرسال',
        
        # ===== رسائل التحقق =====
        'Please select an account type': 'الرجاء اختيار نوع الحساب',
        'Please enter your full name': 'الرجاء إدخال اسمك الكامل',
        'Please enter your email address': 'الرجاء إدخال بريدك الإلكتروني',
        'Please enter a valid email address': 'الرجاء إدخال بريد إلكتروني صحيح',
        'Password must be at least 6 characters': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
        'SSN is required for patient registration': 'رقم الضمان الاجتماعي مطلوب لتسجيل المريض',
        'Please select both commune and specialty': 'الرجاء اختيار البلدية والتخصص',
        'Error finding doctors': 'خطأ في البحث عن الأطباء',
        'You have already selected an account type. Use Back button to change.': 'لقد اخترت نوع حساب بالفعل. استخدم زر الرجوع للتغيير.',
        
        # ===== أزرار التنقل =====
        'Back': 'رجوع',
        'Next': 'التالي',
        'Create Account': 'إنشاء حساب',
        
        # ===== التحقق =====
        'Verify Your Email': 'تحقق من بريدك الإلكتروني',
        "We've sent a verification code to your email": 'لقد أرسلنا رمز التحقق إلى بريدك الإلكتروني',
        'Enter Verification Code': 'أدخل رمز التحقق',
        'Enter the 6-digit code sent to your email': 'أدخل الرمز المكون من 6 أرقام المرسل إلى بريدك',
        'Code expires in': 'ينتهي الرمز خلال',
        'Verify Email': 'تحقق من البريد',
        "Didn't receive the code?": "لم تستلم الرمز؟",
        'Resend Code': 'إعادة إرسال الرمز',
        'Back to Register': 'رجوع إلى التسجيل',
        'Check your spam folder': 'تحقق من مجلد البريد العشوائي',
        'Make sure your email is correct': 'تأكد من صحة بريدك الإلكتروني',
        
        # ===== نسيت كلمة المرور =====
        'No worries! We\'ll send you a reset code': 'لا تقلق! سنرسل لك رمز إعادة التعيين',
        "We'll send a 6-digit verification code to this email": 'سنرسل رمز تحقق مكون من 6 أرقام إلى هذا البريد',
        'Send Reset Code': 'إرسال رمك إعادة التعيين',
        'Back to Login': 'رجوع إلى تسجيل الدخول',
        'We respect your privacy. Your information is secure and will never be shared.': 'نحن نحترم خصوصيتك. معلوماتك آمنة ولن تتم مشاركتها أبداً.',
        
        # ===== إعادة تعيين كلمة المرور =====
        'Reset Password': 'إعادة تعيين كلمة المرور',
        'Enter the code and your new password': 'أدخل الرمز وكلمة المرور الجديدة',
        'Verification Code': 'رمز التحقق',
        'New Password': 'كلمة المرور الجديدة',
        'Confirm Password': 'تأكيد كلمة المرور',
        'Password Requirements:': 'متطلبات كلمة المرور:',
        'At least 6 characters': '6 أحرف على الأقل',
        'Passwords must match': 'كلمات المرور يجب أن تتطابق',
        'Request new code': 'طلب رمز جديد',
        'For security reasons, this link will expire in 10 minutes': 'لأسباب أمنية، سينتهي هذا الرابط خلال 10 دقائق',
        
        # ===== لوحة تحكم الطبيب =====
        'Doctor Dashboard': 'لوحة تحكم الطبيب',
        'Total Patients': 'إجمالي المرضى',
        'Total Reports': 'إجمالي التقارير',
        'Prescriptions': 'الوصفات الطبية',
        'Active Patients': 'المرضى النشطون',
        'Search Filters': 'فلاتر البحث',
        'Patient Name': 'اسم المريض',
        'SSN': 'رقم الضمان',
        'Rx': 'وصفة',
        'Last Report': 'آخر تقرير',
        'Actions': 'إجراءات',
        'Verified': 'تم التحقق',
        'Pending': 'قيد الانتظار',
        'View Reports': 'عرض التقارير',
        'Edit Patient': 'تعديل المريض',
        'New Analysis': 'تحليل جديد',
        'Add Prescription': 'إضافة وصفة',
        'Remove': 'إزالة',
        'No patients found': 'لم يتم العثور على مرضى',
        'Add your first patient': 'أضف مريضك الأول',
        'Add Patient': 'إضافة مريض',
        'Statistics': 'إحصائيات',
        
        # ===== إضافة مريض =====
        'Add New Patient': 'إضافة مريض جديد',
        'Personal Information': 'معلومات شخصية',
        'Create a patient account (with email and password)': 'إنشاء حساب مريض (بريد إلكتروني وكلمة مرور)',
        'The patient will receive a verification code by email': 'سيستلم المريض رمز التحقق عبر البريد الإلكتروني',
        'Same as above if not specified': 'نفس ما سبق إذا لم يتم التحديد',
        'Required only if creating an account': 'مطلوب فقط عند إنشاء حساب',
        'SSN is required when creating an account': 'رقم الضمان مطلوب عند إنشاء حساب',
        'Password must be at least 6 characters': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
        
        # ===== تعديل مريض =====
        'Patient ID': 'رقم المريض',
        'Created': 'تاريخ الإنشاء',
        'Basic Information': 'معلومات أساسية',
        'Medical Information': 'معلومات طبية',
        'Blood Type': 'فصيلة الدم',
        'Select Blood Type': 'اختر فصيلة الدم',
        'Allergies': 'حساسية',
        'e.g., Penicillin, Peanuts, Latex': 'مثال: بنسلين، فول سوداني، لاتكس',
        'Chronic Conditions': 'أمراض مزمنة',
        'e.g., Hypertension, Diabetes, Asthma': 'مثال: ضغط دم، سكري، ربو',
        'Emergency Contact': 'جهة اتصال للطوارئ',
        'Contact Name': 'اسم جهة الاتصال',
        'Full name of emergency contact': 'الاسم الكامل لجهة الاتصال للطوارئ',
        'Contact Phone': 'هاتف جهة الاتصال',
        'Emergency phone number': 'رقم هاتف الطوارئ',
        'Danger Zone': 'منطقة الخطر',
        'Remove this patient from your list': 'إزالة هذا المريض من قائمتك',
        'Remove Patient': 'إزالة المريض',
        'Are you sure you want to remove this patient from your list?': 'هل أنت متأكد من إزالة هذا المريض من قائمتك؟',
        'Patient name is required': 'اسم المريض مطلوب',
        'Email is required for account access': 'البريد الإلكتروني مطلوب للوصول إلى الحساب',
        'SSN cannot be changed after creation': 'رقم الضمان لا يمكن تغييره بعد الإنشاء',
        
        # ===== التحليل الطبي =====
        'Medical Analysis': 'تحليل طبي',
        'Upload Medical Documents': 'رفع المستندات الطبية',
        'Start Analysis': 'بدء التحليل',
        'Save Report': 'حفظ التقرير',
        'Report saved successfully!': 'تم حفظ التقرير بنجاح!',
        'Error saving report': 'خطأ في حفظ التقرير',
        'None identified': 'لم يتم تحديد أي شيء',
        'No alerts': 'لا توجد تنبيهات',
        'Please select images to analyze': 'الرجاء اختيار صور للتحليل',
        'Analysis complete!': 'اكتمل التحليل!',
        'Error during analysis': 'خطأ أثناء التحليل',
        
        # ===== الوصفات الطبية =====
        'New Prescription': 'وصفة طبية جديدة',
        'Diagnosis & Notes': 'التشخيص والملاحظات',
        'Diagnosis': 'التشخيص',
        'Enter diagnosis here...': 'أدخل التشخيص هنا...',
        'Additional Notes': 'ملاحظات إضافية',
        'Additional instructions for the patient...': 'تعليمات إضافية للمريض...',
        'Prescribed Medications': 'الأدوية الموصوفة',
        'Medication': 'الدواء',
        'Dosage': 'الجرعة',
        'Frequency': 'التكرار',
        'Duration': 'المدة',
        'Instructions': 'تعليمات',
        'Select medicine': 'اختر دواء',
        'Select dosage': 'اختر الجرعة',
        'Select frequency': 'اختر التكرار',
        'Select duration': 'اختر المدة',
        'Once daily': 'مرة يومياً',
        'Twice daily': 'مرتين يومياً',
        'Three times daily': 'ثلاث مرات يومياً',
        'Four times daily': 'أربع مرات يومياً',
        'Every 8 hours': 'كل 8 ساعات',
        'Every 12 hours': 'كل 12 ساعة',
        'As needed': 'عند الحاجة',
        'days': 'أيام',
        'e.g., Before meals': 'مثال: قبل الأكل',
        'Add Medication': 'إضافة دواء',
        'AI Drug Interaction Analysis': 'تحليل تفاعلات الأدوية بالذكاء الاصطناعي',
        'AI analyzing drug interactions...': 'الذكاء الاصطناعي يحلل تفاعلات الأدوية...',
        'No dangerous drug interactions detected': 'لم يتم اكتشاف تفاعلات دوائية خطيرة',
        'AI service unavailable. Please check interactions manually.': 'خدمة الذكاء الاصطناعي غير متاحة. يرجى التحقق يدوياً.',
        'Dosage Analysis': 'تحليل الجرعات',
        'Active Ingredient': 'المادة الفعالة',
        'Daily Dose': 'الجرعة اليومية',
        'Safe Limit': 'الحد الآمن',
        'Status': 'الحالة',
        'Warning': 'تحذير',
        'Select medications to analyze': 'اختر الأدوية للتحليل',
        'Save Prescription': 'حفظ الوصفة',
        'At least one medication is required': 'يلزم دواء واحد على الأقل',
        'This prescription may not be safe! Please review.': 'قد لا تكون هذه الوصفة آمنة! يرجى المراجعة.',
        
        # ===== عرض الوصفة =====
        'Medical Prescription': 'وصفة طبية',
        'Prescription No': 'رقم الوصفة',
        'Patient Name': 'اسم المريض',
        'Weight': 'الوزن',
        'Our Services': 'خدماتنا',
        'General Medical Consultations': 'استشارات طبية عامة',
        'Internal Medicine Examinations': 'فحوصات الباطنية',
        'Blood & Urine Analysis': 'تحاليل الدم والبول',
        'ECG (Electrocardiogram)': 'تخطيط القلب (ECG)',
        'Pregnancy Follow-up Clinic': 'متابعة الحمل',
        'Specialized Consultations': 'استشارات متخصصة',
        'Doctor Information': 'معلومات الطبيب',
        'Clinic Information': 'معلومات العيادة',
        "Doctor's Signature": 'توقيع الطبيب',
        'Clinic Stamp': 'ختم العيادة',
        'Dear pharmacist or doctor, for any questions or errors in this prescription, please contact the clinic.': 'زميلي الصيدلي أو الطبيب، أي استفسار أو خطأ في الوصفة، الرجاء الاتصال بالعيادة.',
        
        # ===== إحصائيات الطبيب =====
        'Statistics Dashboard': 'لوحة الإحصائيات',
        'Reports by Month': 'التقارير حسب الشهر',
        'Top Conditions': 'أكثر الحالات شيوعاً',
        'Patient Statistics': 'إحصائيات المرضى',
        'Last Visit': 'آخر زيارة',
        'Export': 'تصدير',
        
        # ===== لوحة تحكم المريض =====
        'Welcome Back': 'مرحباً بعودتك',
        'Here is an overview of your medical records': 'هذه نظرة عامة على سجلاتك الطبية',
        'Medical Reports': 'التقارير الطبية',
        'Doctors': 'الأطباء',
        'AI Analyses': 'تحليلات الذكاء الاصطناعي',
        'Recent Medical Reports': 'التقارير الطبية الأخيرة',
        'My Doctors': 'أطبائي',
        'Recent Prescriptions': 'الوصفات الأخيرة',
        'Medical Alerts': 'تنبيهات طبية',
        'View All Reports': 'عرض جميع التقارير',
        'My Prescriptions': 'وصفاتي الطبية',
        'Report Details': 'تفاصيل التقرير',
        'No medical reports yet': 'لا توجد تقارير طبية بعد',
        'Visit your doctor to get your first analysis': 'زر طبيبك للحصول على أول تحليل',
        'No doctors assigned yet': 'لم يتم تعيين أطباء بعد',
        'No prescriptions yet': 'لا توجد وصفات بعد',
        'View all reports': 'عرض جميع التقارير',
        'View all prescriptions': 'عرض جميع الوصفات',
        'General Practitioner': 'طبيب عام',
        
        # ===== الإعدادات =====
        'Account Settings': 'إعدادات الحساب',
        'Manage your personal information and account preferences': 'إدارة معلوماتك الشخصية وتفضيلات الحساب',
        'Change Password': 'تغيير كلمة المرور',
        'Preferences': 'التفضيلات',
        'Delete Account': 'حذف الحساب',
        'Current Password': 'كلمة المرور الحالية',
        'Update Password': 'تحديث كلمة المرور',
        'Language': 'اللغة',
        'Notifications': 'الإشعارات',
        'Receive email alerts': 'استلام تنبيهات البريد الإلكتروني',
        'Receive appointment reminders': 'استلام تذكيرات المواعيد',
        'Save Preferences': 'حفظ التفضيلات',
        'Are you sure you want to delete your account? This action cannot be undone.': 'هل أنت متأكد من حذف حسابك؟ هذا الإجراء لا يمكن التراجع عنه.',
        'Enter your password to confirm': 'أدخل كلمة المرور للتأكيد',
        'Clinic Logo': 'شعار العيادة',
        'Upload Logo': 'رفع الشعار',
        'Remove Logo': 'حذف الشعار',
        'Recommended size: 200x200px. Formats: PNG, JPG, JPEG, GIF, SVG': 'الحجم الموصى به: 200×200 بكسل. الصيغ: PNG, JPG, JPEG, GIF, SVG',
        'Are you sure you want to remove the clinic logo?': 'هل أنت متأكد من حذف شعار العيادة؟',
        
        # ===== وصفات المريض =====
        'My Prescriptions': 'وصفاتي الطبية',
        'View and manage all your prescriptions': 'عرض وإدارة جميع وصفاتك الطبية',
        'Total Prescriptions': 'إجمالي الوصفات',
        'Active Prescriptions': 'الوصفات النشطة',
        'Expired Prescriptions': 'الوصفات المنتهية',
        'All Prescriptions': 'جميع الوصفات',
        'Active': 'نشط',
        'Expired': 'منتهي',
        'No medications listed': 'لا توجد أدوية مدرجة',
        'Issued on': 'صدر في',
        'Important Information': 'معلومات مهمة',
        'A prescription expires after the indicated validity period': 'تنتهي صلاحية الوصفة بعد المدة المحددة',
        'Contact your doctor for a renewal if needed': 'اتصل بطبيبك للتجديد إذا لزم الأمر',
        'You can print your prescriptions or share them via email': 'يمكنك طباعة وصفاتك أو مشاركتها عبر البريد الإلكتروني',
        'Keep your prescriptions safe and do not share them with unauthorized persons': 'احتفظ بوصفاتك في مكان آمن ولا تشاركها مع أشخاص غير مصرح لهم',
        'Share Prescription': 'مشاركة الوصفة',
        'Enter the email address to share this prescription with:': 'أدخل عنوان البريد الإلكتروني لمشاركة هذه الوصفة مع:',
        'Send': 'إرسال',
        'Prescription sent successfully!': 'تم إرسال الوصفة بنجاح!',
        'Error sending prescription': 'خطأ في إرسال الوصفة',
        'Please enter an email address': 'الرجاء إدخال عنوان بريد إلكتروني',
        'Please enter a valid email address': 'الرجاء إدخال عنوان بريد إلكتروني صحيح',
        
        # ===== أطباء المريض =====
        'List of healthcare professionals managing your medical records': 'قائمة المهنيين الصحيين الذين يديرون سجلاتك الطبية',
        'Total Doctors': 'إجمالي الأطباء',
        'Total Medical Reports': 'إجمالي التقارير الطبية',
        'Your Healthcare Team': 'فريق الرعاية الصحية الخاص بك',
        'Contact': 'اتصال',
        'About Your Healthcare Team': 'حول فريق الرعاية الصحية الخاص بك',
        'Your doctors have access to your medical records': 'أطباؤك لديهم حق الوصول إلى سجلاتك الطبية',
        'They can create prescriptions and medical reports for you': 'يمكنهم إنشاء وصفات طبية وتقارير لك',
        'You can contact them using the email or phone provided': 'يمكنك الاتصال بهم باستخدام البريد الإلكتروني أو الهاتف المقدم',
        'Your medical data is protected and shared only with authorized doctors': 'بياناتك الطبية محمية ولا تتم مشاركتها إلا مع الأطباء المصرح لهم',
        'Doctor Reports': 'تقارير الطبيب',
        'No reports found from this doctor': 'لم يتم العثور على تقارير من هذا الطبيب',
        'Error loading reports': 'خطأ في تحميل التقارير',
        'conditions': 'حالات',
        'medications': 'أدوية',
        'No summary': 'لا يوجد ملخص',
    }
}


def gettext(text, lang=None):
    """دالة الترجمة الرئيسية"""
    if lang is None:
        from flask import session
        lang = session.get('language', 'en')
    
    if lang in translations and text in translations[lang]:
        return translations[lang][text]
    elif text in translations['en']:
        return translations['en'][text]
    return text


def get_current_language():
    """الحصول على اللغة الحالية"""
    from flask import session
    return session.get('language', 'en')


def set_language(lang):
    """تعيين اللغة"""
    if lang in ['en', 'fr', 'ar']:
        from flask import session
        session['language'] = lang
        return True
    return False